export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8 bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="text-center max-w-4xl mx-auto">
        <div className="mb-8">
          <div className="w-16 h-16 bg-blue-600 rounded-xl mx-auto mb-4 flex items-center justify-center">
            <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-4">
            Welcome to TideSpark
          </h1>
          <h2 className="text-xl md:text-2xl text-gray-600 mb-8">
            admin-dashboard Application
          </h2>
        </div>
        
        <div className="bg-white rounded-2xl shadow-xl p-8 mb-8">
          <div className="flex items-center justify-center mb-6">
            <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center">
              <svg className="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
          </div>
          <h3 className="text-2xl font-semibold text-gray-900 mb-4">
            Deployment Successful!
          </h3>
          <p className="text-gray-600 mb-6">
            Your admin-dashboard application is now running successfully on Vercel.
            This is a standalone deployment created from your TideSpark monorepo.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <div className="px-6 py-3 bg-blue-50 rounded-lg">
              <h4 className="font-semibold text-blue-900 mb-1">Framework</h4>
              <p className="text-blue-700">nextjs</p>
            </div>
            <div className="px-6 py-3 bg-green-50 rounded-lg">
              <h4 className="font-semibold text-green-900 mb-1">Status</h4>
              <p className="text-green-700">Live & Running</p>
            </div>
          </div>
        </div>
        
        <p className="text-gray-500 text-sm">
          Generated by TideSpark deployment system
        </p>
      </div>
    </main>
  )
}
